# ????????? ??????????? ? ??
spring.datasource.url=jdbc:mysql://localhost:3306/med_centre?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=po2002li2007na
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA ?????????
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# ???? ???????
server.port=8080